REPORT_NAME     = 'system.domain.name'
CONFIG_INC      = True
CONFIG          = {}
CONFIG_RX       = ''
BRIDGES_INC     = True
BRIDGES         = {}
BRIDGES_RX      = ''
DMRLINK_IP      = '127.0.0.1'
DMRLINK_PORT    = 4321
FREQUENCY       = 10
WEB_SERVER_PORT = 8080
PATH            = './'
PEER_FILE       = 'peer_ids.csv'
SUBSCRIBER_FILE = 'subscriber_ids.csv'
TGID_FILE       = 'talkgroup_ids.csv'
LOCAL_FILE      = 'local_ids.csv'
PEER_URL        = 'http://www.dmr-marc.net/cgi-bin/trbo-database/datadump.cgi?table=repeaters&format=csv&header=0'
SUBSCRIBER_URL  = 'http://www.dmr-marc.net/cgi-bin/trbo-database/datadump.cgi?table=users&format=csv&header=0'